<script>
  import { Container, Row, Col, MaterialApp } from "svelte-materialify";
  import Card from "./Card.svelte";
</script>

<MaterialApp>
  <Container>
    <Row>
      <Col>
        <Card
          headline={"短期売却益狙い銘柄"}
          discription={"月に一度、短期売買銘柄について共有します。"}
          href={"https://www.notion.so/kabu-labo2/e46fb8ca4b944a45867cea50c3122cc2?pvs=4"}
        />
      </Col>
      <Col
        ><Card
          headline={"長期売却益狙い銘柄"}
          discription={"月に一度、長期売買銘柄について考察します。"}
          href={"https://www.notion.so/kabu-labo2/4b86d7f165524a6e80c54a60a8e0ae86?pvs=4"}
        /></Col
      >
    </Row>
    <Row>
      <Col
        ><Card
          headline={"長期配当＆優待狙い銘柄"}
          discription={"月に一度、長期で配当や優待を享受できるイチオシ銘柄を共有します。"}
          href={"https://www.notion.so/kabu-labo2/e3025a5ca57f4ab48643ca1923ca7681?pvs=4"}
        /></Col
      >
      <Col
        ><Card
          headline={"株式投資研究"}
          discription={"月に一度、株式投資関連の研究（有益情報）について紹介します。"}
          href={"https://www.notion.so/kabu-labo2/a1bb1a379d5f4ff9bf13b3199b423731?pvs=4"}
        /></Col
      >
    </Row>

    <Row>
      <Col
        ><Card
          headline={"過去紹介銘柄一覧"}
          discription={"過去、ご紹介した様々な銘柄について一覧共有します。"}
          href={"https://www.notion.so/kabu-labo2/c96b8d32eb824a8fbb6a9e1675158658?pvs=4"}
        /></Col
      >
      <Col
        ><Card
          headline={"メンバーチャット"}
          discription={"メンバー限のチャットへご招待します。"}
          href={"/Chat"}
        /></Col
      >
    </Row>

    <Row>
      <Col
        ><Card
          overline={""}
          headline={"コンサルタント"}
          discription={"オンライン会議で資産運用のコンサルタント。証券アナリスト取得後に行う予定"}
          href={"/Consultant"}
        /></Col
      >
      <Col
        ><Card
          overline={""}
          headline={"blog"}
          discription={"銘柄分析や投資戦略について週一で更新"}
          href={"https://www.notion.so/kabu-labo2/blog-a535213d26df40e9ab452ffd206c1019?pvs=4"}
        /></Col
      >
    </Row>
  </Container>
</MaterialApp>
